import type { Migration } from '../types'

export const MIGRATIONS: Migration[] = [
  {
    version: 1,
    name: 'initial_schema',
    up: [
      `CREATE TABLE IF NOT EXISTS patients (
        id TEXT PRIMARY KEY,
        client_id TEXT UNIQUE NOT NULL,
        server_id TEXT,
        name TEXT NOT NULL,
        gender TEXT NOT NULL,
        birth_date TEXT NOT NULL,
        height_cm REAL,
        weight_kg REAL,
        diagnosis_date TEXT,
        disease_stage TEXT,
        primary_symptom TEXT,
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL,
        sync_status TEXT NOT NULL DEFAULT 'pending'
      )`,
      `CREATE TABLE IF NOT EXISTS tremor_readings (
        id TEXT PRIMARY KEY,
        client_id TEXT UNIQUE NOT NULL,
        server_id TEXT,
        patient_id TEXT NOT NULL,
        device_id TEXT NOT NULL,
        timestamp INTEGER NOT NULL,
        duration_ms INTEGER NOT NULL,
        amplitude_x REAL,
        amplitude_y REAL,
        amplitude_z REAL,
        amplitude_magnitude REAL,
        frequency_hz REAL,
        severity TEXT NOT NULL,
        type TEXT NOT NULL,
        accelerometer_data TEXT,
        gyroscope_data TEXT,
        battery_level INTEGER,
        created_at INTEGER NOT NULL,
        sync_status TEXT NOT NULL DEFAULT 'pending',
        FOREIGN KEY (patient_id) REFERENCES patients(id)
      )`,
      `CREATE TABLE IF NOT EXISTS medications (
        id TEXT PRIMARY KEY,
        client_id TEXT UNIQUE NOT NULL,
        server_id TEXT,
        patient_id TEXT NOT NULL,
        name TEXT NOT NULL,
        generic_name TEXT,
        dosage TEXT NOT NULL,
        frequency TEXT NOT NULL,
        times_per_day INTEGER,
        scheduled_times TEXT,
        start_date TEXT NOT NULL,
        end_date TEXT,
        prescribing_doctor TEXT,
        notes TEXT,
        status TEXT NOT NULL DEFAULT 'active',
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL,
        sync_status TEXT NOT NULL DEFAULT 'pending',
        FOREIGN KEY (patient_id) REFERENCES patients(id)
      )`,
      `CREATE TABLE IF NOT EXISTS medication_records (
        id TEXT PRIMARY KEY,
        client_id TEXT UNIQUE NOT NULL,
        server_id TEXT,
        patient_id TEXT NOT NULL,
        medication_id TEXT NOT NULL,
        scheduled_time INTEGER NOT NULL,
        taken_time INTEGER,
        status TEXT NOT NULL DEFAULT 'scheduled',
        dosage TEXT NOT NULL,
        notes TEXT,
        created_at INTEGER NOT NULL,
        sync_status TEXT NOT NULL DEFAULT 'pending',
        FOREIGN KEY (patient_id) REFERENCES patients(id),
        FOREIGN KEY (medication_id) REFERENCES medications(id)
      )`,
      `CREATE TABLE IF NOT EXISTS devices (
        id TEXT PRIMARY KEY,
        client_id TEXT UNIQUE NOT NULL,
        server_id TEXT,
        name TEXT NOT NULL,
        mac_address TEXT UNIQUE,
        serial_number TEXT UNIQUE,
        firmware_version TEXT,
        hardware_version TEXT,
        model TEXT,
        patient_id TEXT,
        status TEXT NOT NULL DEFAULT 'unpaired',
        paired_at INTEGER,
        last_connected_at INTEGER,
        battery_level INTEGER DEFAULT 0,
        created_at INTEGER NOT NULL,
        updated_at INTEGER NOT NULL,
        sync_status TEXT NOT NULL DEFAULT 'pending',
        FOREIGN KEY (patient_id) REFERENCES patients(id)
      )`,
      `CREATE TABLE IF NOT EXISTS sync_queue (
        id TEXT PRIMARY KEY,
        entity_type TEXT NOT NULL,
        entity_id TEXT NOT NULL,
        operation TEXT NOT NULL,
        priority INTEGER NOT NULL DEFAULT 0,
        retry_count INTEGER NOT NULL DEFAULT 0,
        last_error TEXT,
        created_at INTEGER NOT NULL,
        next_attempt_at INTEGER NOT NULL
      )`,
      `CREATE INDEX IF NOT EXISTS idx_tremor_patient_timestamp ON tremor_readings(patient_id, timestamp DESC)`,
      `CREATE INDEX IF NOT EXISTS idx_tremor_sync_status ON tremor_readings(sync_status)`,
      `CREATE INDEX IF NOT EXISTS idx_medication_patient ON medications(patient_id)`,
      `CREATE INDEX IF NOT EXISTS idx_medication_records_patient_time ON medication_records(patient_id, scheduled_time DESC)`,
      `CREATE INDEX IF NOT EXISTS idx_sync_queue_priority ON sync_queue(priority DESC, created_at ASC)`,
      `CREATE INDEX IF NOT EXISTS idx_sync_queue_entity ON sync_queue(entity_type, entity_id)`,
    ],
  },
]
